### ISSUE TITLE
How can I pass tesseract argument " -c preserve_interword_spaces 1" ?

### ISSUE THREAD

**Issue by languagemaniac** [ocrmypdf/OCRmyPDF#1175] opened 2023-10-21 14:23 UTC
### Describe the bug

Everytime I ocr a japanese pdf I get something like this

漢文 と 日 本 語 の 文 は どこ が 違う の か 

when I should detect this:

漢文と日本語の文はどこが違うのか

When I run tesseract with a pdf page as a png, I specify the argument "-c preserve_interword_spaces=1" along with the rest of the arguments, and it does produce the correct text with no spaces. But I don't know how to do that with ocrmypdf. 

I tried with tesseract-config and supplying it a cfg file with "preserve_interword_spaces 1" written in it, but it doesn't get recognized. 

### Steps to reproduce

Try ocr'ing a japanese pdf I guess, either I'm doing something wrong or it happens to everyone but haven't found anyone talking about this error. Just any japanese pdf comes out with the same error for me.

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

15.3.0

**Comment by jbarlow83** [comment] 2023-10-25 06:46
If you create an invalid tesseract config file such as
```
INVALID__preserve_interword_spaces 1
```

and run

`ocrmypdf --tesseract-config invalidconfigfile in.pdf out.pdf`

then you should get this error message
```
TesseractConfigError: Error occurred while parsing a Tesseract configuration file   
```

which confirms that the (invalid) tesseract file was forwarded to Tesseract, and Tesseract failed to parse the config file. If there is no error, then Tesseract processed your config file successfully.

This makes me think that there is some substantive difference in how the "PDF page as PNG" is rendered compared to the PNG OCRmyPDF creates internally. You could `--keep-temporary-files` to access the temporary files OCRmyPDF creates, and then determine on your own how this differs from the PNG you rendered. 

Also note that [Tesseract 4 omitted this feature but it was reinstated in version 5](https://github.com/tesseract-ocr/tesseract/issues/781). Which Tesseract is installed?

As far as I can determine all config parameters are being passed to tesseract when they should. Unless you provide a test PDF and the exact commands so that I can actually reproduce your issue, there is nothing else I can investigate, so I am closing the issue.

**Comment by languagemaniac** [comment] 2023-10-25 07:45
Hi, I have tesseract 5.3.3 installed, I have created the invalid config file, and I do get the error you mention, so it is getting processed.

I have run the command with the --keep-temporary-files

I found something interesting.

In the temporary files, I found an ocr'd txt file, that doesn't contain spaces, so it is processing the cfg file correctly, but somehow when I select the text in the pdf, it has spaces. So the error seems to be when it creates the pdf file.

Here are some files:

[My test page pdf](https://drive.google.com/file/d/1LokJYmA1UzLkUc3-wxs1SQkP9-b5p9Lq/view?usp=sharing)
[My png generated from the test page with acrobat reader](https://drive.google.com/file/d/1Eym9qfJlit5RtTC5Yl5DaEijLCyYXaQD/view?usp=sharing)
Ocrmypdf tesseract-processed [text file](https://docs.google.com/document/d/15ZCmMVmEKl7FABod2pxQR6n9zTmx5Eqzc5ks7EGz5yk/edit?usp=sharing) I found in the temp files
[Output page](https://drive.google.com/file/d/1FAOU3COeR8dTjAp7rLtQcMK1UoXjRPWC/view?usp=sharing) from ocrmypdf with spaces in the text

here's the full command I runned ocrmypdf:

ocrmypdf --tesseract-config cfg.cfg --keep-temporary-files -l jpn_vert test.pdf output_test.pdf

(with cfg.cfg just containing preserve_interword_spaces 1)

**Comment by jbarlow83** [comment] 2023-10-28 23:21
The attached file was created using

`tesseract -l jpn_vert -c preserve_interword_spaces=1 test.png test_preserve_interword pdf`

[test_preserve_interword.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/13196899/test_preserve_interword.pdf)

which is more or less what OCRmyPDF asks it to produce. As you can see, this PDF produced by Tesseract, without any involvement from OCRmyPDF, has the same problem.

There are many problems with Tesseract's PDF generation and this is one... I am looking into replacing the Tesseract PDF renderer in the hope of addressing some of these issues. For now unfortunately there's not much I can offer.

In "basic PDFs" text is extracted using a heuristic algorithm that guesses where word breaks are supposed to be because, as a printer oriented format, PDFs originally didn't care about extracting text at all. By using some advanced PDF features it is possible to provide more exact information about how the text should appear.

**Closed by jbarlow83** 2023-10-28 23:21 UTC
Labels: bug, need test file

**Comment by languagemaniac** [comment] 2023-10-29 00:56
> The attached file was created using
> 
> `tesseract -l jpn_vert -c preserve_interword_spaces=1 test.png test_preserve_interword pdf`
> 
> [test_preserve_interword.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/13196899/test_preserve_interword.pdf)
> 
> which is more or less what OCRmyPDF asks it to produce. As you can see, this PDF produced by Tesseract, without any involvement from OCRmyPDF, has the same problem.
> 
> There are many problems with Tesseract's PDF generation and this is one... I am looking into replacing the Tesseract PDF renderer in the hope of addressing some of these issues. For now unfortunately there's not much I can offer.
> 
> In "basic PDFs" text is extracted using a heuristic algorithm that guesses where word breaks are supposed to be because, as a printer oriented format, PDFs originally didn't care about extracting text at all. By using some advanced PDF features it is possible to provide more exact information about how the text should appear.

I see, so tesseract does it right when you tell it to output the ocr'd text to a txt file but not when it makes a pdf.

I actually didn't know tesseract could produce pdf files, so I didn't test that and thought it was ocrmypdf issue.

Thank you for taking the time to analyze this.

Unfortunately, looks like the same error happens on more basic pdf where I just have vertical Japanese text and no illustrations.

I'll wait for the update then. Thanks
