### ISSUE TITLE
[Bug]: Ghostscript process fails when running OCRmyPDF on all PDFs

### ISSUE THREAD

**Issue by eoinosullivan** [ocrmypdf/OCRmyPDF#1174] opened 2023-10-20 15:49 UTC
### What were you trying to do?

Installed OCRmyPDF on OSX 13.6 Ventura M1 chip using homebrew
It installed without issue 
When processing PDF image file (A4 page size) it fails every time on Ghostscript (verbose error log below)

Scanning contents: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 52.86page/s]
OCR: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.0/1.0 [00:05<00:00,  5.41s/page]
Postprocessing...
GPL Ghostscript 10.02.0 (2023-09-13)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Unrecoverable error: rangecheck in .putdeviceprops

SubprocessOutputError: Ghostscript PDF/A rendering failed

### Where are you installing from?

Homebrew

### What operating system are you working on?

macOS

### Relevant log output

```plain text
GPL Ghostscript 10.02.0 (2023-09-13)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Unrecoverable error: rangecheck in .putdeviceprops
GPL Ghostscript 10.02.0 (2023-09-13)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Unrecoverable error: rangecheck in .putdeviceprops

ExitCodeException
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 261, in generate_pdfa
    p = run_polling_stderr(
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 100, in run_polling_stderr
    raise CalledProcessError(proc.returncode, args, output=None, stderr=stderr)
subprocess.CalledProcessError: Command '['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=/LeaveColorUnchanged', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/var/folders/3l/wytpqzwn4nz831w96f7774tr0000gq/T/ocrmypdf.io.43j7s9um/fix_docinfo.pdf', '/var/folders/3l/wytpqzwn4nz831w96f7774tr0000gq/T/ocrmypdf.io.43j7s9um/pdfa.ps']' returned non-zero exit status 255.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline
    exec_concurrent(context, executor)
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 302, in exec_concurrent
    pdf = post_process(pdf, context, executor)
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 233, in post_process
    pdf_out = convert_to_pdfa(pdf_out, ps_stub_out, context)
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 735, in convert_to_pdfa
    context.plugin_manager.hook.generate_pdfa(
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 91, in generate_pdfa
    ghostscript.generate_pdfa(
  File "/usr/local/Cellar/ocrmypdf/13.4.2/libexec/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 275, in generate_pdfa
    raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e
ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed
Temporary working files retained at:
/var/folders/3l/wytpqzwn4nz831w96f7774tr0000gq/T/ocrmypdf.io.43j7s9um
```

**Comment by jbarlow83** [comment] 2023-10-21 22:46
I confirmed Ghostscript 10.02.0 (new release) is not an issue.

I'm going to close this because it's a file-specific issue with no test file attached, so there's nothing I can do. 

If you want to reopen, please provide a test file and the exact command line that reproduces the issue. 

If you are concerned about sharing the file publicly, you can encrypt it with my public key as described here:
https://github.com/ocrmypdf/OCRmyPDF/wiki

**Closed by jbarlow83** 2023-10-21 22:46 UTC
Labels: bug

**Comment by eoinosullivan** [comment] 2023-10-22 08:36
Apologies
Attached file for your reference now
[test.zip](https://github.com/ocrmypdf/OCRmyPDF/files/13062741/test.zip)

**Comment by eoinosullivan** [comment] 2023-10-22 08:41
I had a power cut yesterday and the Mac did a full reboot.
When I tested again this morning the same PDF that failed yesterday worked perfectly.
I suspect a full reboot may have sorted the install of ocrmypdf
Please feel free to leave this ticket closed and thanks for responding so quickly in any case

**Comment by tarnoff** [comment] 2024-01-18 23:57
> I have this issue on my Paperless-ngx 1.17.4 this problem is also affecting other users but according to Paperless-ngx 1.17.4 Team this issue cant be fixed in Paperless-ngx Repo and linked this repo [paperless-ngx/paperless-ngx#3933 (comment)](https://github.com/paperless-ngx/paperless-ngx/issues/3933#issuecomment-1669662213). May I ask if you could help ? The file is a ebook from Packt.com and legaly owned.
> 
> The Paperless-ngx 1.17.4 is running as a docker container
> 
> Thank you and best regards Mohamad
> 
> > #[paperless-ngx/paperless-ngx#4116 (comment)](https://github.com/paperless-ngx/paperless-ngx/issues/4116#top)

I'm having the same issue (using OCRmyPDF with the latest Paperless-ngx). I've attached an encrypted file you can use to test on your end.

Here are the relevant logs:

`2024-01-18T23:55:26.249441709Z     ghostscript.generate_pdfa(
2024-01-18T23:55:26.249495359Z   File "/usr/local/lib/python3.11/site-packages/ocrmypdf/_exec/ghostscript.py", line 283, in generate_pdfa
2024-01-18T23:55:26.249547319Z     raise SubprocessOutputError('Ghostscript PDF/A rendering failed') from e
2024-01-18T23:55:26.249603168Z ocrmypdf.exceptions.SubprocessOutputError: Ghostscript PDF/A rendering failed
2024-01-18T23:55:26.249651738Z 
2024-01-18T23:55:26.249689158Z The above exception was the direct cause of the following exception:
2024-01-18T23:55:26.249737618Z 
2024-01-18T23:55:26.249774428Z Traceback (most recent call last):
2024-01-18T23:55:26.249820337Z   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 349, in main_wrap
2024-01-18T23:55:26.249879627Z     raise exc_info[1]
2024-01-18T23:55:26.249919517Z   File "/usr/src/paperless/src/documents/consumer.py", line 446, in try_consume_file
2024-01-18T23:55:26.249952127Z     document_parser.parse(self.working_copy, mime_type, self.filename)
2024-01-18T23:55:26.249978697Z   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 376, in parse
2024-01-18T23:55:26.250121356Z     raise ParseError(
2024-01-18T23:55:26.250153956Z documents.parsers.ParseError: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.
2024-01-18T23:55:26.250189546Z 
2024-01-18T23:55:26.250211176Z The above exception was the direct cause of the following exception:
2024-01-18T23:55:26.250241455Z 
2024-01-18T23:55:26.250263775Z Traceback (most recent call last):
2024-01-18T23:55:26.250289675Z   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
2024-01-18T23:55:26.250326985Z     R = retval = fun(*args, **kwargs)
2024-01-18T23:55:26.250388495Z                  ^^^^^^^^^^^^^^^^^^^^
2024-01-18T23:55:26.250411025Z   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
2024-01-18T23:55:26.250441854Z     return self.run(*args, **kwargs)
2024-01-18T23:55:26.250478794Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T23:55:26.250501574Z   File "/usr/src/paperless/src/documents/tasks.py", line 171, in consume_file
2024-01-18T23:55:26.250530754Z     document = Consumer().try_consume_file(
2024-01-18T23:55:26.250554804Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-18T23:55:26.250576834Z   File "/usr/src/paperless/src/documents/consumer.py", line 474, in try_consume_file
2024-01-18T23:55:26.250604374Z     self._fail(
2024-01-18T23:55:26.250627744Z   File "/usr/src/paperless/src/documents/consumer.py", line 116, in _fail
2024-01-18T23:55:26.250656743Z     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
2024-01-18T23:55:26.250686363Z documents.consumer.ConsumerError: Gregory Hazel Procuration.pdf: Error occurred while consuming document Gregory Hazel Procuration.pdf: SubprocessOutputError: Ghostscript PDF/A rendering failed. See logs for more information.`

Thanks!
[test.zip](https://github.com/ocrmypdf/OCRmyPDF/files/13982676/test.zip)
