### ISSUE TITLE
hocr import / export

### ISSUE THREAD

**Issue by aalmir** [ocrmypdf/OCRmyPDF#453] opened 2019-11-12 12:03 UTC
**Describe the issue**
If you want to create a perfect OCR, 100% correct text, you need some editing function.
For example "gImageReader" gives some basic editing function (but has some other missing features).

**Expected behavior**
An option to export and import hocr.
After export i can make changes on the hocr and import it for PDF creation.

**Comment by adrianbroher** [comment] 2019-11-12 12:34
What a coincidence. I wanted to request the same feature today.

This feature request has some overlap with #177.

**Comment by jbarlow83** [comment] 2019-11-25 08:53
I think this would be great but there's a lot to do to make it work, especially to support after the fact editing.

**Comment by tukusejssirs** [comment] 2021-01-12 19:32
All I would need is an option to merge an hOCR HTML file with a PDF file.

On the Internet, I read about `hocr2pdf` (from [ExactImage](http://exactcode.com/opensource/exactimage/)), which seams not be not developed anymore (and I can’t build it on Fedora 31 for missing `libagg` library → AntiGrain Geometry).

I also found `hocr-pdf` from `hocr-tools`, which I could install from the Fedora repos, but it does not work (it outputs empty file with some header of what).

Finally, gImageReader does output a PDF with hOCR data, but it does not work with 800+ pages (200+ MiB)—it creates a corrupted/damaged PDF (at least that’s what Evince and Adobe Acrobat Reader says).

**Comment by aalmir** [comment] 2021-01-12 19:39
Have you reported this to gImageReader Repo?

**Comment by jbarlow83** [comment] 2021-01-12 19:49
ocrmypdf already has the ability to merge hOCR HTML into PDF through its public APIs. What it does not have is a convenient way to run its post-processing on a set of edited hOCR files.

**Comment by tukusejssirs** [comment] 2021-01-12 20:10
> ocrmypdf already has the ability to merge hOCR HTML into PDF through its public APIs.

Thanks, @jbarlow83, for reply. I haven’t every used `ocrmypdf`; could you guide me how to do accomplish this please? :smiley:

For what I want is to merge hOCR HTML file (generated by gImageReader and `tesseract` and manual correction via gIR and text editor) into a working PDF file merged by ImageMagick. Preferably in terminal, how exactly it does not matter. :smiley:

@aalmir, not exactly. I reported it in [this comment](https://github.com/manisandro/gImageReader/issues/424#issuecomment-758819893) and marginally in manisandro/gImageReader#480.

**Comment by jbarlow83** [comment] 2021-01-12 20:19
@tukusejssirs The relevant code is in hocrtransform.py. See `python -m ocrmypdf.hocrtransform --help`.

**Comment by tukusejssirs** [comment] 2021-01-12 20:43
@jbarlow83, thanks! Is there any way to either input multiple images or pre-created PDF file? `hocrtransform.py` has `-i`option, but it looks like it accepts only one image file, however, I have 800+ images (or pages in a PDF) and a single hOCR file containing all the text data (note: not all pages have text, some are blank and therefore there is no mention of them in the hOCR file).

@aalmir, the issue is here → manisandro/gImageReader#486.

**Comment by jbarlow83** [comment] 2021-01-12 20:56
No, it doesn't have that ability, but you could split the hOCR and run a loop.

**Comment by tukusejssirs** [comment] 2021-01-15 12:48
@jbarlow83, I have just tried to merge hOCR data and an image into a PDF, but it failed (see below). Am I missing some kind of module or something?

[Here](https://github.com/jbarlow83/OCRmyPDF/files/5820520/hocr2pdf_test_files.zip) are the test files.

Note that although I want to output the interword spaces, I don’t want them where I have commented out the whitespace between `span`s. This is due to the fact that I don’t want a space to be output after `&shy;` (soft hyphen). This is just a hack as I could not find a better way to deal with hyphens.

<details>
  <summary><code>python -m ocrmypdf.hocrtransform -i 024_mr2004.tif --interword-spaces 024_hocr.html merged.pdf</code></summary>

```bash
/usr/lib64/python3.8/runpy.py:127: RuntimeWarning: 'ocrmypdf.hocrtransform' found in sys.modules after import of package 'ocrmypdf', but prior to execution of 'ocrmypdf.hocrtransform'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/ocrmypdf/hocrtransform.py", line 382, in <module>
    hocr = HocrTransform(args.hocrfile, args.resolution)
  File "/usr/lib/python3.8/site-packages/ocrmypdf/hocrtransform.py", line 68, in __init__
    self.hocr = ElementTree.parse(hocrFileName)
  File "/usr/lib64/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: undefined entity: line 45, column 113
```
</summary

**Comment by jbarlow83** [comment] 2021-01-15 19:34
It looks like the XML (`024_hocr.html`) is invalid, specifically at line 45.

**Comment by tukusejssirs** [comment] 2021-01-15 20:21
@jbarlow83, do I get it right that you say the a soft hyphen (`&shy;`) is invalid in hOCR file? As I understand it, the [hOCR specification 1.2](http://kba.cloud/hocr-spec/1.2/#hyphenation) says otherwise:

> ### 5.6. Hyphenation
>
> Soft hyphens must be represented using the HTML `&shy;` entity.

**Comment by jbarlow83** [comment] 2021-01-15 20:38
ocrmypdf.hocrtransform is only capable of parsing the subset of hOCR generated by Tesseract.

For this specific case, you'll need to add a string like the following to the top of the hOCR file

```xml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
            "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" [
            <!ENTITY shy '#x00AD'>
            ]>
```

Based on:
https://stackoverflow.com/questions/35591478/how-to-parse-html-with-entities-such-as-nbsp-using-builtin-library-elementtree

And U+00AD being the Unicode code point for soft hyphen.

**Comment by jbarlow83** [comment] 2021-01-15 20:39
(Note that doctype signature may actually be incorrect for hOCR; whatever the hOCR spec says is correct should be used.)

**Comment by tukusejssirs** [comment] 2021-01-15 20:59
Thanks, @jbarlow83, that _sort of_ worked.

1. I change the doctype in the example document to the following:

```html
<!DOCTYPE html [
	<!ENTITY shy '#x00AD'>
	<!ENTITY thinsp '#x2009'>
]>
```

2. Run your script, which succeded with two warnings (see below).

<details>
  <summary><code>python -m ocrmypdf.hocrtransform -i 024_mr2004.tif --interword-spaces 024_hocr.html merged.pdf</code></summary>

```bash
/usr/lib64/python3.8/runpy.py:127: RuntimeWarning: 'ocrmypdf.hocrtransform' found in sys.modules after import of package 'ocrmypdf', but prior to execution of 'ocrmypdf.hocrtransform'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
/usr/lib/python3.8/site-packages/ocrmypdf/hocrtransform.py:109: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for child in element.getchildren():
```
</details>

3. After opening `merge.pdf` in a PDF reader, the hOCR text is there, however, the `ENTITY` definitions make those characters in the text literal, e.g. `&shy;` is replaced with `#x00AD` (6 characters) instead of a real soft hyphen.

4. Base on [this comment](https://stackoverflow.com/questions/35591478/how-to-parse-html-with-entities-such-as-nbsp-using-builtin-library-elementtree#comment110461097_35591479) to that SO question, I’ve even tried to change the definition to `<!ENTITY shy '&amp;shy;'>`, but it failed the same way. Same with the doctype you used in your example.

**Comment by jbarlow83** [comment] 2021-01-15 21:11
Official definition is
```xml
<!ENTITY shy    CDATA "&#173;" -- soft hyphen = discretionary hyphen,
                                  U+00AD ISOnum -->
```

From: https://www.w3.org/TR/html4/sgml/entities.html

**Comment by tukusejssirs** [comment] 2021-01-15 21:29
Thanks again, @jbarlow83, but `CDATA` causes an error using `ocrmypdf.hocrtransform` (same command as above).

1. Change the doctype to the following (the doctype itself does not matter):

```bash
<!DOCTYPE html [
	<!ENTITY shy    CDATA "&#173;" -- soft hyphen = discretionary hyphen, U+00AD ISOnum -->
	<!ENTITY thinsp "&#2009;">
]>
```

2. Run the `ocrmypdf.hocrtransform` command (same as above). This produces an error on the L2C17 character (2nd space before `CDATA` on `shy` entity definition.

<details>
  <summary><code>python -m ocrmypdf.hocrtransform -i 024_mr2004.tif --interword-spaces 024_hocr.html merged.pdf</code></summary>

```bash
/usr/lib64/python3.8/runpy.py:127: RuntimeWarning: 'ocrmypdf.hocrtransform' found in sys.modules after import of package 'ocrmypdf', but prior to execution of 'ocrmypdf.hocrtransform'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/ocrmypdf/hocrtransform.py", line 382, in <module>
    hocr = HocrTransform(args.hocrfile, args.resolution)
  File "/usr/lib/python3.8/site-packages/ocrmypdf/hocrtransform.py", line 68, in __init__
    self.hocr = ElementTree.parse(hocrFileName)
  File "/usr/lib64/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: syntax error: line 2, column 17
```

**Comment by jbarlow83** [comment] 2021-01-15 21:50
Remove the -- and the comments
after it.

**Comment by jbarlow83** [comment] 2021-01-15 22:56
```xml
<!DOCTYPE html [
	<!ENTITY shy    CDATA "&#173;">
	<!ENTITY thinsp "&#2009;">
]>
```

**Comment by tukusejssirs** [comment] 2021-01-15 23:10
@jbarlow83, I’ve already tried that; same result as I posted in my last comment.

It is quite interesting to me that your parser (or whatever reports tnat error) says the error occurs on a space (the second one before `CDATA`). Can’t there be an error in the parser?

**Comment by jbarlow83** [comment] 2021-01-15 23:32
The parser is just Python's widely used XML parser from the standard library (`xml.etree.ElementTree`). It's saying your modified input file is not valid XML anymore so it won't parse.  It seems to work if you remove the CDATA bit.

```python
import xml.etree.ElementTree as ET
x = ET.fromstring(
    """
    <!DOCTYPE html [
	<!ENTITY shy     "&#173;">
	<!ENTITY thinsp "&#2009;">
    ]>
<test>&shy;</test>"""
)
assert x.text == '\xad'
```

**Comment by tukusejssirs** [comment] 2021-01-16 13:06
@jbarlow83, thanks, that helped for soft hyphens, but not for thin spaces. Thin spaces are replaced with `■` (U+25A0) for some reason. However, when I use your Python code (modified a bit; see below), it outputs U+07D9 (`ߙ`; Nko Letter Ra) for some reason. Note that I don’t code in Python at all.

<details>
  <summary>test_html_entity.py</code></summary>

```python
#!/bin/python

"""
Test HTML entities in ElementTree
"""
import xml.etree.ElementTree as ET
x = ET.fromstring(
	"""
	<!DOCTYPE html [
		<!ENTITY shy     "&#173;">
		<!ENTITY thinsp "&#2009;">
	]>
<test>&thinsp;</test>"""
)

if x.text == '\xe2\x80\x89':
	print('true')
else:
	print('false')


print('input  : [ ]', format(ord(' '), 'x'))
print('output : [' + x.text + ']', format(ord(x.text), 'x'))
```
</details>

**Comment by jbarlow83** [comment] 2021-01-17 21:58
What you're trying to do likely requires software development beyond this one issue. You'll need to find someone who can do that coding for you.

**Comment by tukusejssirs** [comment] 2021-01-17 22:09
Okay, thanks anyway for the help. :smiley:

**Comment by rmast** [comment] 2021-11-07 20:04
> If you want to create a perfect OCR, 100% correct text, you need some editing function. For example "gImageReader" gives some basic editing function (but has some other missing features).

I don't know whether gscan2pdf uses gImageReader for it, but in gscan2pdf I get a possibility to visually alter the OCR'ed text, based on the HOCR, and visually showing the confidence with colors.

**Comment by jaysonlarose** [comment] 2022-07-13 03:25
Apologies if this is already answered, but I've been digging around for a few days and haven't found a definitive answer for this:

What's the best/easiest/recommended way to

* get OCRmyPDF to process something[^1] up to the point where it's performed OCR but hasn't yet merged the OCR text into a PDF, and output the optimized artifacts as well as the OCR data
* get OCRmyPDF to take the data created from the previous step and merge everything together into a finished PDF

In other words, use OCRmyPDF in a workflow where a human can come in and hand-correct (and quite possibly version control) the OCR data before performing the merge?  I've been playing around with running something like `img2pdf *.png | ocrmypdf - -k --tesseract-config hocr --deskew --clean ../output.pdf`, but it outputs a lot of stuff that isn't really necessary to the workflow and tends to get quite large (6.1G worth of source files generates 55G worth of artifacts).  That, and I'm not quite sure how to get OCRmyPDF to pick the process back up afterwards.

I'm fine with digging around in the code if necessary... in fact, that's probably where I'm going to be going after I finish writing this.  I just figured I'd ask first in case someone has the answers close at hand.

Thanks,
--Jays

[^1]: (I read somewhere that OCRmyPDF is happiest with the output of `img2pdf <image files> |`[^2] but am happy to change that if it's not the case)

[^2]: My current workflow consists of scanning a document as .png files, collating them so that they sort ASCIIbetically, and then running `img2pdf *.png | ocrmypdf - --deskew --clean output.pdf`.

**Comment by jbarlow83** [comment] 2022-07-13 08:58
There are no great options for hand-correction because I tend to see as a problem a command line program is not well equipped to solve. I suppose I could insert a plugin hook that allows a custom renderer at src/ocrmypdf/_sync.py:216. Then you could intercept the .hocr file and make edits to it before proceeding with the standard hocrtransform. The pages would come at you out of order, because ocrmypdf processes pages in parallel.

**Comment by rmast** [comment] 2022-07-13 09:53
You might be interested in the flow of GScan2pdf, which offers a scanned text-edit feature:

https://images.pling.com/img/00/00/49/49/34/1230285/43c303619853d3cf57804eb721a0abac19d8.png

However I don’t believe it supports PDF/A or MRC compression(plugin).

**Comment by jaysonlarose** [comment] 2022-07-13 10:11
@rmast Checking it out now. It's going to be chewing on the 214 MiB 324-page PDF I just fed it for a while, but what it's showing while it processes each page is making me optimistic. Well, besides looking a little bit like a ransom letter, but I can understand that considering how each word seems to be in its own bounding box, and that's just kind of how things are.

**Comment by jaysonlarose** [comment] 2022-07-13 11:11
GScan2pdf almost works. It gets up to saving page 35 of 324, and then it just sits there. The UI is still responsive, it claims to be saving, but it's just... sitting there..

**Comment by jaysonlarose** [comment] 2022-07-15 05:18
@jbarlow83 I just tossed you $200USD via OpenCollective in hopes that I can shamelessly bribe you to add some method for hocr export/import.

I just spent the last couple of hours learning about postfix operators, and it's a rabbit hole I *really* don't want to have to go down.

**Comment by jaysonlarose** [comment] 2022-07-15 05:18
See? I just said "postfix" when I meant "PDF".

**Comment by jbarlow83** [comment] 2022-07-18 07:59
@jaysonlarose I do appreciate the generous contribution and I'll try to think if there's something clever/efficient/reasonable for a CLI app.

**Comment by rmast** [comment] 2022-10-11 08:17
I’m even surprised it reads an existing PDF. Usually I cut PDF’s into loose pictures to process them, for example with pdfimages -tiff.

As GScan2PDF will not apply JBIG2 there’s no need to put all of them in one PDF at the end for getting one big dictionary, you’ll need more steps to get it compressed.

pdsfam will split or merge PDF’s for you.

**Comment by lumalav** [comment] 2023-09-02 23:06
@jaysonlarose, I needed something exactly to what you are describing and I forked the repo. In my version, ocrmypdf can be used in two different workflows: 

1. ocronly is performed with the ability of outputting the hocr file (`--pdf-renderer hocr --ocr-only --hocr-out /some/path`)
2. ocronly is performed but the merge is done by some hocr that is coming from a different source (`--pdf-rended hocr --hocr-in /some/path `)

However, I don't think I'll be opening a pull request because of the way I implemented option 2. It needs to perform ocr again in case optimizations where done in the middle (--deskew or --rotation) so the hocr that is being passed could match the optimizations that are being done in the moment. Additionally, option 2 loses the sidecar because this one is created only if hocr is performed in the original flow.

I'll be waiting for my 200 bucks :)

[link](https://github.com/lumalav/OCRmyPDF/commit/573dd1b0e2f18b69e53cb574e0d3573f3e78bb24) to my commit

**Comment by jbarlow83** [comment] 2023-11-12 08:52
Now implemented as an experimental API

**Closed by jbarlow83** 2023-11-12 08:52 UTC
Labels: enhancement

**Comment by endolith** [comment] 2024-02-17 22:50
> @jaysonlarose
> 
> I had the same problem as you. I wanted to edit the OCR before merging it to a PDF. This is what i did.
> 
>     * ran ocrmypdf with `-k` and` --pdf-renderer hocr`
> 
>     * edit hocr-files to your liking
> 
>     * move all .png and .hocr to folder (make sure that they have exact same filename i.e. 00001.png and 00001.hocr)
> 
>     * `git clone https://github.com/rescribe/bookpipeline`
> 
>     * `cd bookpipeline/cmd/pdfbook`
> 
>     * `go build pdfbook`
> 
>     * `./pdfbook folder output.pdf`

Why do we need a separate tool when ocrmypdf already does this step internally?
