### ISSUE TITLE
ocrmypdf --tesseract-timeout=0 --deskew blocks deskewing - was:  Using ocrmypdf to correct the deviation has no effect No errors were reported

### ISSUE THREAD

**Issue by wss1801** [ocrmypdf/OCRmyPDF#966] opened 2022-05-18 08:42 UTC
Using ocrmypdf to correct the deviation has no effect No errors were reported？
**This is the source file of the test**
[11.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/8714688/11.pdf)

ocrmypdf --tesseract-timeout=0 --deskew --output-type pdf -l chi_sim c:\test\11.pdf c:\test\output-10.pdf
![1652862879(1)](https://user-images.githubusercontent.com/34929437/168995346-a85e92d6-d342-43a4-8ef2-d2dea526c0a8.png)

**There is no change after optimization through the command line, as shown in the following figure:**
Please see what's wrong with this?
![1652863857(1)](https://user-images.githubusercontent.com/34929437/168998714-8bfe4b4b-5c7f-4ff6-899e-b3a2f73862f3.png)

**Comment by jbarlow83** [comment] 2022-05-18 18:00
On second thought, the issue is that `--tesseract-timeout 0` prevents detection of the skew angle, since that feature depends on Tesseract.

**Comment by wss1801** [comment] 2022-05-19 02:00
Can you test it for me? My source file is on it

**Comment by deexpabada** [comment] 2022-12-15 19:46
I think I have the same issue. I'm trying to deskew without applying any OCR, but no deskew is being applied if `--tesseract-timeout=0`. It does successfully deskew if `--tesseract-timeout` is not 0. However, I don't want the PDF OCRed.

**Comment by jbarlow83** [comment] 2023-06-02 08:18
Fixed as of v14.1.0

**Closed by jbarlow83** 2023-06-02 08:18 UTC
Labels: bug
