### ISSUE TITLE
[Bug]: PDF/A-3B files generated with a widely used commercial encoder generate garbage OCR content

### ISSUE THREAD

**Issue by jce-zz** [ocrmypdf/OCRmyPDF#1118] opened 2023-06-21 07:44 UTC
### Describe the bug

I'm using OCRmyPDF as part of the Paperless-NGX document management application. Since a few weeks, I noticed that some OCR'd PDF documents do not contain any clear text anymore but only some random garbage Unicode characters. (see attached screenshot)

Upon investigation it became clear, that this is somehow related to commercially created PDFs coming e.g. from banks, insurances, etc. 

There are several commonalities with the affected files, even that they come from different companies:
- They are compliant to PDF/A-3B standard
- They are created with the same PDF SDK (4-Heights® PDF Processing SDK; http://www.pdf-tools.com)

Earlier, when the same files were processed fine, they were created with another version of the same SDK form the same vendor: 3-Heights™ PDF to PDF/A Converter API. However, they are also PDF/A-3B documents.

I suspect something in the output of this SDK is not working correctly. So, how can we get this working again?

### Steps to reproduce

```plain text
Here's the output of the command that Paperless-NGX runs in the background, run interactively on the command line:

root@1be5a04be1d0:/usr/src/paperless/data# ocrmypdf --output-type pdfa --skip-text --deskew --rotate-pages --rotate-pages-threshold 12 --sidecar ocr.txt 2023-06-15\ Salt\ Mobile\ SA.pdf some-output.pdf
Scanning contents: 100%|| 3/3 [00:00<00:00, 47.37page/s]
Start processing 3 pages concurrently
    1 skipping all processing on this page                                                                                                                                    
    2 skipping all processing on this page                                                                                                                                    
    3 skipping all processing on this page                                                                                                                                    
OCR: 100%|| 3.0/3.0 [00:00<00:00, 818.51page/s]
Postprocessing...
PDF/A conversion: 100%|| 3/3 [00:00<00:00, 10.61page/s]
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
Recompressing JPEGs: 0image [00:00, ?image/s]
Deflating JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.00 savings: 0.1%
Output file is a PDF/A-2B (as expected)
```

### Files

OCR output generated from these affected files:
![2023-06-15_13h37_27](https://github.com/ocrmypdf/OCRmyPDF/assets/121529/3eac9b06-d22c-4ff0-9ca9-e605de065df1)

### OCRmyPDF version

14.2.1

### Relevant log output

```plain text
root@1be5a04be1d0:/usr/src/paperless/data# ocrmypdf -v1 --output-type pdfa --skip-text --deskew --rotate-pages --rotate-pages-threshold 12 --sidecar ocr.txt 2023-06-15\ Salt\ Mobile\ SA.pdf some-output2.pdf
ocrmypdf 14.2.1
Running: ['tesseract', '--version']
Found tesseract 5.3.0
Running: ['tesseract', '--version']
Running: ['gs', '--version']
Found gs 10.00.0
Running: ['gs', '--version']
Running: ['tesseract', '--list-langs']
stdout/stderr = List of available languages in "/usr/share/tesseract-ocr/5/tessdata/" (6):
deu
eng
fra
ita
osd
spa

os.symlink(2023-06-15 Salt Mobile SA.pdf, /tmp/ocrmypdf.io.gylqswlb/origin)
os.symlink(/tmp/ocrmypdf.io.gylqswlb/origin, /tmp/ocrmypdf.io.gylqswlb/origin.pdf)
Scanning contents: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 45.42page/s]
Using Tesseract OpenMP thread limit 1
Start processing 3 pages concurrently
    1 skipping all processing on this page                                                                                                                                    
    2 skipping all processing on this page                                                                                                                                    
    1 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                        
    3 skipping all processing on this page                                                                                                                                    
    1 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                    
    2 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                        
    2 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                    
    3 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0                                                                                        
    3 Page rotation: (content, auto) -> page = (0, 0) -> 0                                                                                                                    
OCR: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.0/3.0 [00:00<00:00, 423.58page/s]
/tmp/ocrmypdf.io.gylqswlb/sidecar.txt -> ocr.txt
Postprocessing...
os.symlink(/tmp/ocrmypdf.io.gylqswlb/graft_layers.pdf, /tmp/ocrmypdf.io.gylqswlb/fix_docinfo.pdf)
Running: ['gs', '--version']
Running: ['gs', '-dBATCH', '-dNOPAUSE', '-dSAFER', '-dCompatibilityLevel=1.6', '-sDEVICE=pdfwrite', '-dAutoRotatePages=/None', '-sColorConversionStrategy=LeaveColorUnchanged', '-dAutoFilterColorImages=true', '-dAutoFilterGrayImages=true', '-dJPEGQ=95', '-dPDFA=2', '-dPDFACompatibilityPolicy=1', '-o', '-', '-sstdout=%stderr', '/tmp/ocrmypdf.io.gylqswlb/fix_docinfo.pdf', '/tmp/ocrmypdf.io.gylqswlb/pdfa.ps']
GPL Ghostscript 10.0.0 (2022-09-21)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 3.
Page 1                                                                                                                                                                        
Page 2                                                                                                                                                                        
Page 3                                                                                                                                                                        
PDF/A conversion: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 10.30page/s]
Running: ['tesseract', '--version']
Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
The following metadata fields were not copied: {'{http://ns.adobe.com/pdf/1.3/}PDFVersion', '{http://ns.adobe.com/xap/1.0/mm/}History', '{http://ns.adobe.com/xap/1.0/}MetadataDate', '{http://ns.adobe.com/xap/1.0/mm/}InstanceID'}
Optimizable images: JPEGs: 0 PNGs: 0
Recompressing JPEGs: 0image [00:00, ?image/s]
Deflating JPEGs: 0image [00:00, ?image/s]
Optimizable images: JBIG2 groups: 0
JBIG2: 0item [00:00, ?item/s]
os.symlink(/tmp/ocrmypdf.io.gylqswlb/optimize.opt.pdf, /tmp/ocrmypdf.io.gylqswlb/optimize.pdf)
Running: ['jbig2', '--version']
Running: ['pngquant', '--version']
Optimize ratio: 1.00 savings: 0.1%
/tmp/ocrmypdf.io.gylqswlb/optimize.pdf -> some-output2.pdf
Output file is a PDF/A-2B (as expected)
```

**Comment by jbarlow83** [comment] 2023-06-21 07:59
Please attach an example input PDF. I don't have the ability to set up the environment that produced these files easily.

My random guess is that there's an issue in Ghostscript 10.00.0 and if you try a more recent Ghostscript the issue will be resolved.

**Comment by jce-zz** [comment] 2023-06-21 08:07
The problem is, that all the affected files contain sensitive personal data that I don't want to/cannot share publicly here right now. I'm still waiting for a less sensitive document to appear to share here.

**Comment by jbarlow83** [comment] 2023-06-21 09:13
Yes, that's often the case. If you like you could encrypt a file to my GPG public key as described here:
https://github.com/ocrmypdf/OCRmyPDF/wiki
(and then zip the .gpg file, because GitHub doesn't allow .gpg uploads)

**Comment by stumpylog** [comment] 2023-06-22 16:15
Regarding the Ghostscript version, that's what Bookworm released with: https://packages.debian.org/bookworm/ghostscript

Even testing and unstable don't have a newer Ghostscript yet, though there is a new release from the upstream

**Comment by jce-zz** [comment] 2023-08-03 06:32
The issue is still present and I'm waiting for a suitable file to share. Unfortunately, the third-party libraries that create the files with issues are mostly used by insurances, banks etc. which documents I can't really share to the public. :-(

**Comment by solariz** [comment] 2023-08-08 13:51
I [might have the same problem](https://github.com/paperless-ngx/paperless-ngx/discussions/3954#discussioncomment-6669692) - at least outcome looks same. If it helps I can share a PDF privately of it because it is "just" my internet bill no company stuff.

**Comment by jbarlow83** [comment] 2023-08-08 20:38
@solariz Yes, I can't work on this without a reproducing PDF.
If you like you could encrypt a file to my GPG public key as described here:
https://github.com/ocrmypdf/OCRmyPDF/wiki
(and then zip the .gpg file, because GitHub doesn't allow .gpg uploads)

**Comment by solariz** [comment] 2023-08-09 07:11
@jbarlow83 

My gpg wont let me encrypt it due the key in your link is expired.
```
gpg --list-key 8EA702B420664133
pub   ed25519 2020-05-19 [SC] [expired: 2023-05-19]
      7270A56980543E957377F8478EA702B420664133
```

**Comment by jbarlow83** [comment] 2023-08-09 07:35
Thanks.
I updated by GPG on the keyserver so the expiry date should be updated for future uses.

Unfortunately I could not reproduce the garbage OCR output using vodafone.zip and @jce-zz 's  command
```
ocrmypdf --output-type pdfa --skip-text --deskew --rotate-pages --rotate-pages-threshold 12 --sidecar ocr.txt in.pdf output.pdf
```

That is, the input and output text both appear as expected in Evince and Popper, and copy/paste correctly. Input/output PDFs also renders correctly in PDF.js. I would say if there are rendering errors, the fault lies with the PDF viewer not the PDF; despite the error in the font, most viewers seem able to view the PDF.

Regarding PDF/A and verapdf (linked paperless-ngx issue):
- The document claims PDF/A-**1b** conformance, not 1a, hence some of the errors; it is correct for Acrobat to say the document does not form to 1a
- There is some error in the fonts

veraPDF reports (and I don't know what this means exactly):
```
Aug. 09, 2023 12:27:47 A.M. org.verapdf.pd.font.type1.Type1PrivateParser decodeCharString
WARNING: Error in parsing private data in Type 1 font: incorrect amount of charstings specified.
Aug. 09, 2023 12:27:47 A.M. org.verapdf.pd.font.type1.Type1PrivateParser decodeCharString
WARNING: Error in parsing private data in Type 1 font: incorrect amount of charstings specified.
```

**Comment by solariz** [comment] 2023-08-09 07:40
Thanks for having a look into it. I also didnt figured out what they do with their PDF, obviously vodafone dont care much about standards because even my Adobe Acrobat is complaining about the fonts. I guess getting them to fix it is like talking to a wall so I will find some workaround I can automate to convert them. Again thanks for having a look into it.

**Comment by jbarlow83** [comment] 2023-08-09 07:51
If you can coax paperless-ngx into using --force-ocr on files that match specific criteria that would fix it by reconstructing the PDF. I don't know if they have this feature.

**Comment by jce-zz** [comment] 2023-08-09 14:53
Ok, I will look into it and get on touch with the Paperless folks.

I also might have a candidate file for you to check. I finally got a less sensitive bill that I could probably share. I‘ll validate the issue and then get back to you.

**Comment by saua** [comment] 2024-01-06 13:54
I've got basically the same issue with another official and overly private-data rich PDF, but "luckily" I can still reproduce the issue if I just cut off the last (static) page (which may or may not mess up any PDF/A spec, but the issue at hand still reproduces with this file). I've attached it here (still encrypted, since I'm a bit paranoid about any metadata that stuck around): [test.zip](https://github.com/ocrmypdf/OCRmyPDF/files/13849890/test.zip)

This reproduces the issue with the latest jbarlow83/ocrmypdf-alpine docker image. And I just tested it: with jbarlow83/ocrmypdf it does NOT reproduce the issue, but shows the text correctly, which reinforces the idea that this is a problem in some dependency.

**Comment by jce-zz** [comment] 2024-01-06 14:01
@saua Thanks for staying behind this issue! I also still experience it, but still don’t have any document without sensitive data to share. What is clear is, that all docs with issues are from the same source, which uses some commercial PDF library to generate the docs. Would be so happy, if it could be finally overcome! 😀

**Comment by saua** [comment] 2024-01-06 16:44
I've now dug into this issue as much as I can and it's complicated:

- it (my version at least) shows up on the official jbarlow83/ocrmypdf-alpine docker image
- it does NOT show up when using the jbarlow83/ocrmypdf docker image
- it DOES show up when using the paperless-ngx images 2.1 and 2.3 (I know this is not super-relevant here, but I'd like to note it for reasons that might become apparent later).

Since obviously both the -alpine and non-alpine images use the same ocrmypdf source, the problem has to be in some of the dependencies, so I tried to hunt down the relevant differences.

One notable one is that -alpine uses Ghostscript 10 but the Ubuntu version uses GS 9. However, this (alone) doesn't seem to be the source of the problem, since I rebuilt the ubuntu image based on Ubuntu 23.04 (and even Debian  bookworm) which uses GS10 as well, and it's working.

The fact that the problem does NOT show up on Debian bookworm based builds made me curious, because paperless-ngx builds its images based on bookworm as well, so I dug into it and found that paperless-ngx uses their own build of ghostscript (and a few other images).

Building a version of their docker image without their custom builds fixed the issue for me!

Now this puts me into the weird situation of where this bug should really be raised/tracked:

- it seems to come from some dependency of this package, which IMO means that this could/should check for the issue and maybe raise some minimum version dependency
- it can be reproduced in ONE of the official docker images, but not the other
- it happens in paperless-ngx with heir own self-built dependencies, which suggests they should look into it as well...

**Comment by stumpylog** [comment] 2024-01-06 17:05
From paperless, the "custom" version isn't customized at all.  It's built from Debain's sources, just grabbed from trixie instead of bookworm to provide faster bug fixes to users of our image.

**Comment by saua** [comment] 2024-01-06 17:33
Yeah, I knew that but thought that maybe something went wrong in that combination.

But it turns out I have been following a red herring, because apparently paperless-ngx 2.3 does not actually have the problem, I just hadn't fully reloaded when I tried it ... my bad.

**Comment by jce-zz** [comment] 2024-01-06 22:08
You have the same problem, it’s the content recognized in the OCR and visible in the content tab. Not the visual rendering.

I actually upgraded to the latest version just few days ago and had some documents re-OCRed. Did not change anything. Do I need to trigger something different?

**Comment by jbarlow83** [comment] 2024-01-07 09:05
My testing

| Image | GS version | OCRmyPDF | Reproduced gibberish? |
| --- | --- | ---| --- |
| regular install | 10.02.1 | 16.0.3+ | no |
| Alpine hash a258beafc667 | 10.02.0 | 16.0.2 | yes
| Ubuntu hash f82ad236a204 | 9.55 | 16.0.3+ | no

I thought it would be unlikely 10.02.0/10.02.1 would matter, but it turns out that Ghostscript 10.02.1 contains the following fix
https://git.ghostscript.com/?p=ghostpdl.git;a=commit;h=41d02e3c101e929e12eca346c8004b725341a475
From that commit description I would say it is quite problem that is the cause of the problem. It certainly could cause misinterpretation of characters.

It's a change that applies to Ghostscript's new PDF rendering introduced in 10.0, so 9.x and >=10.02.01 should be fine.

The issue can be reproduced on Alpine's Ghostscript without OCRmyPDF and without PDF/A conversion - just passing the through Ghostscript will corrupt the text:
```
docker run -i --rm --entrypoint /usr/bin/gs -v (pwd):/input -v (pwd)/tmp:/output  jbarlow83/ocrmypdf-alpine  -sDEVICE=pdfwrite -o /output/out.pdf /input/1118.saua2.pdf
```

Alpine doesn't have 10.02.1 yet, so we will have to wait for that fix.

I suppose I will have to put in a warning for Ghostscript <10.02.1.

Thanks to everyone who helped investigate.

**Closed by jbarlow83** 2024-01-07 09:05 UTC
Labels: bug

**Comment by jce-zz** [comment] 2024-04-10 13:47
Is there any update on this? Do we know when the dependencies will be updated? Thanks!

**Comment by webmogul1** [comment] 2025-03-27 14:29
> You have the same problem, it’s the content recognized in the OCR and visible in the content tab. Not the visual rendering.
> 
> I actually upgraded to the latest version just few days ago and had some documents re-OCRed. Did not change anything. Do I need to trigger something different?

Is this still a issue?
I am having the same problem with some bank statements.

**Comment by jce-zz** [comment] 2025-03-27 16:36
> Is this still a issue? I am having the same problem with some bank statements.

Yes, it's the same issue forever. Nothing changed. Many bills coming via the electronic bill system render fine but OCR only shows garbage. No idea how to get that fixed, as all these document contain sensitive personal data and I don't want to share. :-(

**Comment by jbarlow83** [comment] 2025-03-27 17:02
I understand the frustration, but for users still experiencing this issue, it stems from a bug in Ghostscript 10.2.0, which many Linux distributions still deliver. There’s nothing left I can do from this codebase to resolve it—it needs to be addressed by upgrading this dependency.

As a reminder, maintaining open-source software requires significant time and resources, and I do this voluntarily. If the current pace of issue resolution isn’t meeting your needs, you’re welcome to contribute—whether through code, testing, documentation, or [financial support through Open Collective](https://opencollective.com/james-barlow). Every bit of help allows maintainers to prioritize fixes faster.

This issue is already closed because it is not actionable.

Thanks for your understanding.

**Comment by webmogul1** [comment] 2025-03-27 18:01
> I understand the frustration, but for users still experiencing this issue, it stems from a bug in Ghostscript 10.2.0, which many Linux distributions still deliver. There’s nothing left I can do from this codebase to resolve it—it needs to be addressed by upgrading this dependency.
> 
> As a reminder, maintaining open-source software requires significant time and resources, and I do this voluntarily. If the current pace of issue resolution isn’t meeting your needs, you’re welcome to contribute—whether through code, testing, documentation, or [financial support through Open Collective](https://opencollective.com/james-barlow). Every bit of help allows maintainers to prioritize fixes faster.
> 
> This issue is already closed because it is not actionable.
> 
> Thanks for your understanding.

I am running Ghostscript 10.04.0. But I have the same issue.
The issue only happens if I set paperless to output as PDF/A. If I set it to PDF the issue is gone.

**Comment by jbarlow83** [comment] 2025-03-27 18:07
@webmogul1 
If you have a reproducible example with a test file, then open a new issue with it and provide it there. I have already explained options for sharing files that may contain personal information. 
If you cannot share a reproducible example, please don't bother opening an issue, because there's no way I would be able to investigate it.

**Comment by jce-zz** [comment] 2025-04-03 13:56
I opened a new issue with an example file attached. Hope this helps!
