### ISSUE TITLE
Enhancement: page number: display as integers vs floats 

### ISSUE THREAD

**Issue by macdeport** [ocrmypdf/OCRmyPDF#901] opened 2022-01-19 20:48 UTC
**Is your feature request related to a problem? Please describe.**
Currently the page number is displayed as float on my installation.

![ocrmypdf-float-integer-220119](https://user-images.githubusercontent.com/26068595/150210966-a9566b60-37f5-4cdb-be0e-3da0d0cc0ee9.jpg)

**Describe the solution you'd like**
If this is not due to my bad setting I suggest to display the page number of as an integer

**Comment by jbarlow83** [comment] 2022-01-19 22:10
Pages get marked as half done (+0.5) when they're done the "map" step of a parallel operation and another +0.5 when they're done the "reduce" step. So this is a little odd perhaps but it is by design.

**Comment by macdeport** [comment] 2022-01-20 08:00
Of course it is only a question of aesthetics and even visual ergonomics: I personally took some time to realize that "33.0" was indeed the number of pages of the document...

This one being static can be displayed without difficulty as integer .

Moreover, for the page being OCRed, the two phases that must be usefully distinguished, can be displayed in a sequence 
" 0.5" " 1 " " 1.5" " 2 " ... "33 " that clearly indicates two distinct phases.

**Comment by jbarlow83** [comment] 2022-01-21 22:11
I agree it would be nicer to use integers but the progress bar is a third party library. Not worth pursuing at this time.

**Closed by jbarlow83** 2022-01-21 22:11 UTC
