### ISSUE TITLE
[Bug]: JBIG2 corruption of scanned pages & some pages overwriting other pages

### ISSUE THREAD

**Issue by gwern** [ocrmypdf/OCRmyPDF#1150] opened 2023-09-15 17:55 UTC
### Describe the bug

Optimizing a particular [old scanned paper](https://www.rangevoting.org/HylZeck1980.pdf) results in the first page being visually corrupted with open spaces in letters replaced by solid black, and then also additional corruption like the first page replacing several subsequent pages (which seem to disappear entirely). There are no error messages or warnings I notice aside from the common 'lots of diacritics' one.

This happens with `--redo-ocr --optimize 3 --jbig2-lossy` but not `--redo-ocr --optimize 3` nor `--redo-ocr`, so it seems to be the JBIG2 code at fault.

### Steps to reproduce

```plain text
1. `wget 'https://www.rangevoting.org/HylZeck1980.pdf' && ormypdf --optimize 3 --jbig2-lossy --redo-ocr HylZeck1980.pdf HylZeck1980-small-jbig2.pdf`
```

### Files

[HylZeck1980-small-jbig2.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/12622337/HylZeck1980-small-jbig2.pdf)
[HylZeck1980-small.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/12622338/HylZeck1980-small.pdf)
[1980-hylland-corrupt.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/12622340/1980-hylland-corrupt.pdf)
[HylZeck1980-ocred.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/12622341/HylZeck1980-ocred.pdf)
[HylZeck1980-original.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/12622343/HylZeck1980-original.pdf)

### OCRmyPDF version

11.7.3; jbig2enc 0.28

**Comment by jbarlow83** [comment] 2023-09-15 18:11
With JBIG2 lossy, you are accepting that some lossy results like this will occur. I've never seen one that bad, mind you. But in any case, the answer is to not use that feature if it generates unacceptable results.

**Comment by gwern** [comment] 2023-09-15 19:13
If it was just the black dots, I would leave it at that, yes - 'wow, that's unusually bad, but I guess lossy compressor gonna loss, and this is why I quickly check PDFs manually post-compression' - but overwriting the following pages, deleting them and destroying the overall structure of the PDF, seems like a big deal. That goes way beyond what I would expect from a lossy compressor!

**Comment by jbarlow83** [comment] 2023-09-17 20:55
On my system using the latest ocrmypdf and jbig2enc 0.28 from the Ubuntu 22.04 PPA, there are no issues when reproducing optimization using the command you supplied. The output PDF is well formed and does not even have the issue with open spaces in letters being filled.

Your file 1980-hylland-corrupt does not seem to be corrupt in any way that I can see.

[issue1150_current.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/12643703/_.pdf)

I'm going to close the issue since it seems to be related to old versions.

**Closed by jbarlow83** 2023-09-17 20:55 UTC
Labels: bug
