### ISSUE TITLE
[Feature]: Add parameter to ignore "Invalid rotation" errors from img2pdf

### ISSUE THREAD

**Issue by iohann95** [ocrmypdf/OCRmyPDF#1155] opened 2023-09-19 13:20 UTC
### Describe the proposed feature

Hello,
I have several JPEGs that came from an Android app.

If I try to convert them,
`ocrmypdf --image-dpi=72 example.jpg example.pdf`

It gives me an error: `Invalid rotation (0)`
```Input file is not a PDF, checking if it is an image...
Input file is an image
Input image has no ICC profile, assuming sRGB
Image seems valid. Try converting to PDF...
An exception occurred while executing the pipeline
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ocrmypdf/_sync.py", line 365, in run_pipeline
    origin_pdf = triage(
  File "/usr/lib/python3/dist-packages/ocrmypdf/_pipeline.py", line 142, in triage
    triage_image_file(input_file, output_file, options)
  File "/usr/lib/python3/dist-packages/ocrmypdf/_pipeline.py", line 98, in triage_image_file
    img2pdf.convert(
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 2263, in convert
    ) in read_images(
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 1484, in read_images
    color, ndpi, imgwidthpx, imgheightpx, rotation, iccp = get_imgmetadata(
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 1286, in get_imgmetadata
    raise ExifOrientationError("Invalid rotation (%d)" % value)
img2pdf.ExifOrientationError: Invalid rotation (0)
```

That seems to be a common error from JPEGs that come from Android apps.
If I open `_pipeline.py` and add `rotation=img2pdf.Rotation.ifvalid` on the `img2pdf.convert()` call, it ignores the error and is able to OCR the file without any problems. 

It would be nice to be possible to skip those errors using a parameter, since that don't stop the file from being able to be OCR'd.

Thank you very much!

**Comment by jbarlow83** [comment] 2023-09-19 21:06
Can you check if you using img2pdf 0.4.4?
It looks like ocrmypdf uses the appropriate arguments to avoid this error, but that's only an option if 0.4.4 is installed.

**Comment by jbarlow83** [comment] 2023-09-19 23:59
I confirmed is fixed in current versions. The next version of ocrmypdf will drop support for img2pdf < 0.4.4, in commit e27f2a19

**Closed by jbarlow83** 2023-09-19 23:59 UTC
Labels: enhancement
