### ISSUE TITLE
[Bug]: Warning: "xref 473: While extracting this image, an error occurred"

### ISSUE THREAD

**Issue by macdeport** [ocrmypdf/OCRmyPDF#1293] opened 2024-04-12 18:14 UTC
### Describe the bug

Numerous warnings/tracebacks concerning image extraction when processing a PDF file.

### Steps to reproduce

```plain text
Run ocrmypdf -v1 --output-type pdf -O2 --jbig2-lossy --skip-text bid\$.pdf bid.pdf
```

### Files

[bid$.pdf](https://github.com/ocrmypdf/OCRmyPDF/files/14961942/bid.pdf)
[bid$.json](https://github.com/ocrmypdf/OCRmyPDF/files/14961947/bid.json)
[ocrmypdf-log-240412.txt.zip](https://github.com/ocrmypdf/OCRmyPDF/files/14961976/ocrmypdf-log-240412.txt.zip)

### OCRmyPDF version

16.1.2

### Relevant log output

```plain text
Running: ['tesseract', '--version']
Found tesseract 5.3.3
Running: ['tesseract', '--version']
Running: ['pngquant', '--version']
Found pngquant 3.0.3
Running: ['jbig2', '--version']
Found jbig2 0.28
Running: ['gs', '--version']
Found gs 10.3.0
Running: ['gs', '--version']
Running: ['tesseract', '--list-langs']
stdout/stderr = List of available languages in "/opt/local/share/tessdata/" (3):
eng
fra
osd

pikepdf mmap enabled
os.symlink(bid$.pdf, /var/folders/ps/z7flxvdj3b97p9_07lknl6dc0000gn/T/ocrmypdf.io.bhfwxkze/origin)
os.symlink(/var/folders/ps/z7flxvdj3b97p9_07lknl6dc0000gn/T/ocrmypdf.io.bhfwxkze/origin, /var/folders/ps/z7flxvdj3b97p9_07lknl6dc0000gn/T/ocrmypdf.io.bhfwxkze/origin.pdf)
pikepdf mmap enabled
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Using Tesseract OpenMP thread limit 3
pikepdf mmap enabled
    1 skipping all processing on this page
    1 Text rotation: (text, autorotate, content) -> text misalignment = (0, 0, 0) -> 0
    1 Page rotation: (content, auto) -> page = (0, 0) -> 0
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Postprocessing...
Running: ['tesseract', '--version']
Recursing into Form XObject /X139 in page 0
Recursing into Form XObject /X70 in page 0
Recursing into Form XObject /X48 in page 0
Recursing into Form XObject /X56 in page 0
Recursing into Form XObject /X310 in page 0
Recursing into Form XObject /X275 in page 0
xref 482: skipping image because it is an SMask
xref 439: treating as an optimization candidate
Recursing into Form XObject /X81 in page 0
Recursing into Form XObject /X246 in page 0
Recursing into Form XObject /X102 in page 0
Recursing into Form XObject /X162 in page 0
Recursing into Form XObject /X190 in page 0
Recursing into Form XObject /X207 in page 0
Recursing into Form XObject /X138 in page 0
Recursing into Form XObject /X156 in page 0
Recursing into Form XObject /X178 in page 0
Recursing into Form XObject /X211 in page 0
Recursing into Form XObject /X249 in page 0
Recursing into Form XObject /X281 in page 0
xref 485: skipping image because it is an SMask
xref 442: treating as an optimization candidate
Recursing into Form XObject /X283 in page 0
xref 486: skipping image because it is an SMask
xref 443: treating as an optimization candidate
Recursing into Form XObject /X110 in page 0
Recursing into Form XObject /X100 in page 0
Recursing into Form XObject /X132 in page 0
Recursing into Form XObject /X160 in page 0
Recursing into Form XObject /X89 in page 0
Recursing into Form XObject /X66 in page 0
Recursing into Form XObject /X111 in page 0
Recursing into Form XObject /X94 in page 0
Recursing into Form XObject /X145 in page 0
Recursing into Form XObject /X287 in page 0
Recursing into Form XObject /X72 in page 0
Recursing into Form XObject /X177 in page 0
Recursing into Form XObject /X43 in page 0
Recursing into Form XObject /X222 in page 0
Recursing into Form XObject /X311 in page 0
Recursing into Form XObject /X39 in page 0
Recursing into Form XObject /X119 in page 0
Recursing into Form XObject /X154 in page 0
Recursing into Form XObject /X64 in page 0
Recursing into Form XObject /X298 in page 0
Recursing into Form XObject /X148 in page 0
Recursing into Form XObject /X196 in page 0
Recursing into Form XObject /X164 in page 0
Recursing into Form XObject /X38 in page 0
Recursing into Form XObject /X45 in page 0
Recursing into Form XObject /X149 in page 0
Recursing into Form XObject /X135 in page 0
Recursing into Form XObject /X226 in page 0
Recursing into Form XObject /X79 in page 0
Recursing into Form XObject /X93 in page 0
Recursing into Form XObject /X58 in page 0
Recursing into Form XObject /X199 in page 0
Recursing into Form XObject /X242 in page 0
Recursing into Form XObject /X198 in page 0
Recursing into Form XObject /X42 in page 0
Recursing into Form XObject /X116 in page 0
Recursing into Form XObject /X29 in page 0
xref 456: treating as an optimization candidate
xref 470: treating as an optimization candidate
...
xref 288: While extracting this image, an error occurred
Traceback (most recent call last):
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/ocrmypdf/optimize.py", line 323, in extract_images
    result = extract_fn(
             ^^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/ocrmypdf/optimize.py", line 180, in extract_image_generic
    result = extract_image_filter(image, xref)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/ocrmypdf/optimize.py", line 93, in extract_image_filter
    and first_filtdp[1].get(Name.Predictor, 1) == 1
        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
xref 447: While extracting this image, an error occurred
Traceback (most recent call last):
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/ocrmypdf/optimize.py", line 323, in extract_images
    result = extract_fn(
             ^^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/ocrmypdf/optimize.py", line 180, in extract_image_generic
    result = extract_image_filter(image, xref)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/ocrmypdf/optimize.py", line 93, in extract_image_filter
    and first_filtdp[1].get(Name.Predictor, 1) == 1
        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
...
Optimizable images: JPEGs: 0 PNGs: 0
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Recursing into Form XObject /X139 in page 0
Recursing into Form XObject /X70 in page 0
Recursing into Form XObject /X48 in page 0
Recursing into Form XObject /X56 in page 0
Recursing into Form XObject /X310 in page 0
Recursing into Form XObject /X275 in page 0
xref 482: skipping image because it is an SMask
xref 439: treating as an optimization candidate
Recursing into Form XObject /X81 in page 0
Recursing into Form XObject /X246 in page 0
Recursing into Form XObject /X102 in page 0
Recursing into Form XObject /X162 in page 0
Recursing into Form XObject /X190 in page 0
Recursing into Form XObject /X207 in page 0
Recursing into Form XObject /X138 in page 0
Recursing into Form XObject /X156 in page 0
Recursing into Form XObject /X178 in page 0
Recursing into Form XObject /X211 in page 0
Recursing into Form XObject /X249 in page 0
Recursing into Form XObject /X281 in page 0
xref 485: skipping image because it is an SMask
xref 442: treating as an optimization candidate
Recursing into Form XObject /X283 in page 0
...
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/ocrmypdf/optimize.py", line 93, in extract_image_filter
    and first_filtdp[1].get(Name.Predictor, 1) == 1
        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
PNGs                  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Recursing into Form XObject /X139 in page 0
Recursing into Form XObject /X70 in page 0
Recursing into Form XObject /X48 in page 0
Recursing into Form XObject /X56 in page 0
Recursing into Form XObject /X310 in page 0
Recursing into Form XObject /X275 in page 0
xref 482: skipping image because it is an SMask
xref 439: treating as an optimization candidate
...
Optimizable images: JBIG2 groups: 0
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Image optimization did not improve the file - optimizations will not be used
Running: ['jbig2', '--version']
Running: ['pngquant', '--version']
Image optimization ratio: 1.00 savings: -0.3%
Total file size ratio: 1.01 savings: 0.6%
/var/folders/ps/z7flxvdj3b97p9_07lknl6dc0000gn/T/ocrmypdf.io.bhfwxkze/optimize.pdf -> bid$_.pdf
```

**Comment by jbarlow83** [comment] 2024-04-16 07:30
Duplicate of #1271

**Closed** 2024-04-16 07:30 UTC
Labels: bug
