### ISSUE TITLE
copy multiple fonts through grafting process

### ISSUE THREAD

**Issue by kkrell2016** [ocrmypdf/OCRmyPDF#874] opened 2021-12-15 21:17 UTC
I am writing a plugin to use google vision for ocr as tesseract has some problems for my use case.

I always get an error message from Ghostscript that a font is unknown. It was hard to find out why.
It's because _graft.py just looks for one font and then continues. Would it be possible to copy every font from the ocr.pdf? There are several fonts as reportlib replaces some characters.

The problem is more a visual one, because the pdf is still created at the end.

**Comment by jbarlow83** [comment] 2021-12-15 22:37
_graft assumes a text only PDF produced by Tesseract. I haven't looked at what PDF output are produced by Cloud Vision. More adjustments may be required than simply changing how fonts are copied.

You could also consider parsing the JSON and using something like hocrtransform to produce a suitable PDF.

**Comment by kkrell2016** [comment] 2021-12-16 01:46
Thank you for the quick answer.

That's exactly what I'm doing right now.
I parse the JSON to HOCR, load it into hocrtransform and use the to_pdf function to get the pdf.

The problem lies in the way how reportlab works, which simply exchanges some special characters and writes them into the document with ZapfDingbats. Didn't find a function in reportlab to prevent this.
Maybe i just filter them out in near future.

Tesseract does not have the problem, because it has it's own engine and just ignores

**Comment by jbarlow83** [comment] 2021-12-16 07:49
The issue is that PDF itself predates Unicode and doesn't have an automatic way of including a font that covers all of Unicode. It does have builtin fonts for most western European languages and the dingbats.

If AGPL is not an issue you could try using PyMuPDF to generate the PDF - as a newer library it may be easier to get Unicode support working.

Tesseract's approach was to create a "glyphless" font, a font that covers all of Unicode but maps every character to an empty space. Unfortunately, PDF viewers have trouble with this, but it's still viable. Someone wrote a Python version of the Tesseract PDF renderer here (https://git.archive.org/merlijn/archive-pdf-tools/-/blob/master/internetarchivepdf/pdfrenderer.py) which may be a way of getting a Tesseract-like textonly PDF.

**Comment by jbarlow83** [comment] 2022-03-13 08:01
Closing due to age

**Closed by jbarlow83** 2022-03-13 08:01 UTC
