### ISSUE TITLE
[Bug]:  NotImplementedError in colorspace

### ISSUE THREAD

**Issue by macdeport** [ocrmypdf/OCRmyPDF#1376] opened 2024-08-13 18:46 UTC
### Describe the bug

```ocrmypdf --output-type pdf --redo-ocr in.pdf bid.pdf```
Using the given PDF file this produces ```NotImplementedError``` in colorspace

### Files

[in.pdf.zip](https://github.com/user-attachments/files/16603841/in.pdf.zip)

### How did you download and install the software?

PyPI (pip, poetry, pipx, etc.)

### OCRmyPDF version

16.4.3

### Relevant log output

```plain text
$ocrmypdf --output-type pdf --redo-ocr in.pdf bid.pdf
Scanning contents     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
    1 redoing OCR                                                                                                                                                _pipeline.py:327
OCR                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Postprocessing...                                                                                                                                                      ocr.py:144
Linearizing           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 100/100 0:00:00
xref 24: While extracting this image, an error occurred                                                                                                           optimize.py:330
Traceback (most recent call last):                                                                                                                                               
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ocrmypdf/optimize.py", line 326, in extract_images                             
    result = extract_fn(                                                                                                                                                         
             ^^^^^^^^^^^                                                                                                                                                         
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ocrmypdf/optimize.py", line 209, in extract_image_generic                      
    and pim.colorspace in pim.SIMPLE_COLORSPACES                                                                                                                                 
        ^^^^^^^^^^^^^^                                                                                                                                                           
  File "/Users/alain/Library/Python/3.11/lib/python/site-packages/pikepdf/models/image.py", line 210, in colorspace                                                              
    raise NotImplementedError(                                                                                                                                                   
NotImplementedError: not sure how to get colorspace: ['/Indexed', ['/CalRGB', pikepdf.Dictionary({                                                                               
  "/Gamma": [ Decimal('2.22'), Decimal('2.22'), Decimal('2.22') ],                                                                                                               
  "/Matrix": [ Decimal('0.41239'), Decimal('0.21264'), Decimal('0.01933'), Decimal('0.35758'), Decimal('0.71517'), Decimal('0.11919'), Decimal('0.18045'),                       
Decimal('0.07218'), Decimal('0.9504') ],                                                                                                                                         
  "/WhitePoint": [ Decimal('0.95043'), 1, Decimal('1.09') ]                                                                                                                      
})], 255,                                                                                                                                                                        
b'\xe7\x88\x93\xf3\xc4\xc9\xe0kx\xf9\xe2\xe5\xce\x11&\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00                
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\                
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x                
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0                
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00                
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\                
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x                
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0                
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00                
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\                
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x                
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0                
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00                
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\                
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x                
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0                
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00                
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\                
x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x                
00\x00']                                                                                                                                                                         
Recompressing JPEGs   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Deflating JPEGs       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
JBIG2                 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0/0 -:--:--
Image optimization ratio: 1.00 savings: 0.0%                                                                                                                     _pipeline.py:989
Total file size ratio: 1.02 savings: 2.0%                                                                                                                        _pipeline.py:992
$


```
```

**Comment by jbarlow83** [comment] 2024-08-14 08:35
This is actually a pikepdf issue and will be fixed in pikepdf 9.1.2

**Closed by jbarlow83** 2024-08-14 08:35 UTC
Labels: triage

**Comment by macdeport** [comment] 2024-08-14 10:29
Thank you for OCRmyPDF and his patient updating and improvement.

**Comment by macdeport** [comment] 2024-08-21 13:33
Still present with in `py311-pikepdf @9.1.2_0` (MacPorts)

**Comment by jbarlow83** [comment] 2024-08-21 22:29
Works for me - I can reproduce the issue by switching pikepdf versions. Perhaps ocrmypdf isn't using the installed pikepdf directly?

**Comment by macdeport** [comment] 2024-08-22 08:17
You are right...

`Python 3.11.9 / ocrmypdf 16.4.3 / pikepdf 9.1.1`

despite (`MacPorts` install):

```
$port installed ocrmypdf
The following ports are currently installed:
  ocrmypdf @16.4.2_0+python311
  ocrmypdf @16.4.3_0+python311 (active)

$port installed py311-pikepdf
The following ports are currently installed:
  py311-pikepdf @9.1.0_0
  py311-pikepdf @9.1.1_0
  py311-pikepdf @9.1.2_0 (active)


```

**Comment by macdeport** [comment] 2024-08-25 08:59
Fixed, works on my side too: sorry, it was a conflict over an old pip installation... Thank you.
